#!/bin/bash

docker-compose up -d

# Wait for the /readyz endpoint to return a successful response
while true; do
    response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/readyz)
    if [ "$response" -eq 200 ]; then
        break
    else
        echo "Waiting for app service to be ready..."
        sleep 5
    fi
done

for i in {1..10}
do
    echo "GET request for data record $i"
    curl -X GET http://localhost:8080/data/$i

    echo "PUT request for data record $i"
    curl -X PUT -H "Content-Type: application/json" -d '{"id":'$i', "name":"New Name"}' http://localhost:8080/data/$i
done
